### ISSUE TITLE
Dont functorize over Cohttp_lwt.Client

### ISSUE THREAD

**Issue by rgrinberg** [marklrh/otter#4]
just define your own small signature (some subset of `Cohttp_client.Client` perhaps) and functorize over that.

The reason for this is that somebody might want to alter the client implementation by providing their own (lwt based) client. One use case for this would be to provide a client that reuses the same connection under the hood for example.

**Comment by marklrh** [comment]
makes sense. i'll define another more generalized signature so people can use their own client, like async maybe.

**Comment by marklrh** [comment]
merged via pull request #6
